### ISSUE TITLE
Failed broadcast detection on /26 subnet

### ISSUE THREAD

**Issue by jkrcma** [EvanPurkhiser/prolink-go#8]
Function `getBroadcastAddress` returns incorrect address inside my network. Had to hardcode the IP address to make it working for my show.

```
# ip a
19: eth0@if20: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:16:3e:bc:fa:7d brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 192.168.1.21/26 brd 192.168.1.63 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::216:3eff:febc:fa7d/64 scope link
       valid_lft forever preferred_lft forever
```
```
# tcpdump -n dst port 50000 and udp
listening on enp4s0, link-type EN10MB (Ethernet), capture size 262144 bytes
20:53:49.854088 IP 192.168.1.7.50000 > 192.168.1.63.50000: UDP, length 54
20:53:50.231466 IP 192.168.1.3.54140 > 192.168.1.63.50000: UDP, length 54
20:53:50.413371 IP 192.168.1.9.50000 > 192.168.1.63.50000: UDP, length 54
20:53:50.942529 IP 192.168.1.21.50000 > 192.168.1.255.50000: UDP, length 54
20:53:51.854022 IP 192.168.1.7.50000 > 192.168.1.63.50000: UDP, length 54
20:53:52.238930 IP 192.168.1.3.54161 > 192.168.1.63.50000: UDP, length 54
20:53:52.415743 IP 192.168.1.9.50000 > 192.168.1.63.50000: UDP, length 54
20:53:52.442461 IP 192.168.1.21.50000 > 192.168.1.255.50000: UDP, length 54
```
`.3` is a desktop PC with Rekordbox
`.7` is DJM-900NXS
`.9` is CDJ-2000NXS
`.21` is _prolink-overlay_ virtual machine

**Comment by EvanPurkhiser** [comment]
Yeah I'm aware of this.. it's actually kind of tricky to get the *real* network mask from an interface.. Go only gives me back the default mask.

**Comment by EvanPurkhiser** [comment]
Actually I was wrong, you can get the mask and this was easier than I suspected :)

**Comment by brunchboy** [comment]
Have you seen any of the stuff I have been committing to dysentery and Beat Link lately? I am now able to take over the tempo and beat grid, so Beat Link Trigger can make CDJs sync to Ableton Link (as well as the other direction which as worked almost since Ableton Link was released). You can tell players to load tracks and start or stop playing, or become tempo master or turn sync on or off. Now I am figuring out how to navigate the menu tree that dbserver provides, and just implemented the ability to search the database by a text substring.

**Comment by brunchboy** [comment]
Ah! I just saw some of your other issues, and that you are implementing some of the new stuff. Fun! 😁

**Comment by brunchboy** [comment]
That sounds like a great plan. I get questions sometimes from people wanting to do live stream overlay stuff, now I know I should send them your way.

If you are using web sockets over the loopback interface, rather than going over an actual network, it might be fast enough. I have to do that in order to talk to my Carabiner daemon to synchronize with Ableton Link, both to bridge between the Java and C++ runtimes, and between the Eclipse and GPL license realms.

I wish when I started writing Beat Link Trigger I had realized it was going to be more than a demonstration project for other people who might want to use my Beat Link library; now it is my most-downloaded project by far, and I wish I could separate the UI from the core engine to make it easier for people who want to run it headless, but it was thrown together in a rapid prototyping way that means that separation will require a complete rewrite today, and I’d always rather be adding new features instead.
